### ISSUE TITLE
ExceptionInInitializerError - Buildning the configuration network gives an error

### ISSUE THREAD

**Issue by DanielMartensson** [eclipse/deeplearning4j#8071] opened 2019-08-02 21:05 UTC
#### Issue Description

I'm trying to create a graphical interface for DeepLearning4J by using OpenJFX. 
But when I try to build a neural network with DL4J, I get this error when I try build the configuration.

It happens here
```

public class DL4JModel {

	/*
	 * Objects
	 */
	private ListBuilder listBuilder;
	private MultiLayerNetwork multiLayerNetwork;
	
	public DL4JModel(ListBuilder listBuilder) {
		this.listBuilder = listBuilder;
	}
	
	/*
	 * Build model
	 */
	public void buildModel() {
		multiLayerNetwork = new MultiLayerNetwork(listBuilder.build()); // <---- HERE!
	}

}
```

I first create the global configuration, then the layers and then build it.

```
public class DL4J {
	
	/*
	 * Deeplearning4J objects
	 */
	private Builder globalConfig;
	private ListBuilder listBuilder;
	
	/*
	 * Deeplearning4J methods in other classes
	 */
	private DL4JGlobalConfig dL4JGlobalConfig;
	private DL4JLayers dL4JLayers;
	private DL4JModel dL4JModel;
	private DL4JSaveLoad dl4JSaveLoad;

	public DL4J(){
		/*
		 * Global configurations and layer holder
		 */
		globalConfig = new NeuralNetConfiguration.Builder(); // Our global configuration for neural network
		listBuilder = new NeuralNetConfiguration.ListBuilder(globalConfig); // This hold layers
		
		/*
		 * Then create objects for our under classes
		 */
		dL4JGlobalConfig = new DL4JGlobalConfig(globalConfig);
		dL4JLayers = new DL4JLayers(listBuilder);
		dL4JModel = new DL4JModel(listBuilder);
		dl4JSaveLoad = new DL4JSaveLoad(dL4JModel);
		
	}
	
	/*
	 * Create an initial neural network model
	 */
	public void initialModel() {
		// Configurations
		dL4JGlobalConfig.setSeed(new Random().nextInt(100) + 300); // Set random number 100-300
		dL4JGlobalConfig.setOptimizationAlgorithm(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT); // Set default optimization algorithm
		dL4JGlobalConfig.setRegularization("L1", 0.5); // L1-Regularization with 0.5
		dL4JGlobalConfig.setUpdater(new Adam()); //  Adam updater
		dL4JGlobalConfig.setWeightInit(WeightInit.XAVIER); // Initial weights
		// Layers
		dL4JLayers.addDenseLayer(5, 10, Activation.RELU); // Input layer
		dL4JLayers.addOutputLayer(10, 5, Activation.RELU, LossFunction.NEGATIVELOGLIKELIHOOD); // Output layer
		// Model
		dL4JModel.buildModel(); // Build model now - No more are required <--- HERE i build
	}
}
```

The DL4JGlobalConfig class looks like this:
```
package se.danielmartensson.deeplearning;

import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration.Builder;
import org.deeplearning4j.nn.weights.WeightInit;
import org.nd4j.linalg.learning.config.IUpdater;


/**
 * This class will handle the global configurations inside the neural network 
 */
public class DL4JGlobalConfig {
	
	/*
	 * Objects
	 */
	private Builder globalConfig;
	
	public DL4JGlobalConfig(Builder globalConfig) {
		this.globalConfig = globalConfig;
	}

	/*
	 * Set this to a random number to improved repeatability 
	 */
	public void setSeed(long seed) {
		globalConfig.setSeed(seed);
	}
	
	/*
	 * Set the optimization algorithm
	 */
	public void setOptimizationAlgorithm(OptimizationAlgorithm optimizationAlgo) {
		globalConfig.optimizationAlgo(optimizationAlgo);
	}
	
	/*
	 * Set the updater
	 */
	public void setUpdater(IUpdater updater) {
		globalConfig.updater(updater);
	}
	
	/*
	 * Set the regularization and its number
	 */
	public void setRegularization(String LX, double number) {
		if(LX.equals("L1"))
			globalConfig.l1(number);
		else
			globalConfig.l2(number);
	}
	
	/*
	 * Set the weight init
	 */
	public void setWeightInit(WeightInit weightInit) {
		globalConfig.weightInit(weightInit);
	}
	
}
```

The DL4JLayers class looks like this
```
package se.danielmartensson.deeplearning;

import org.deeplearning4j.nn.conf.NeuralNetConfiguration.ListBuilder;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.lossfunctions.LossFunctions.LossFunction;

/**
 * This class is made for creations of the layers
 */
public class DL4JLayers {

	/*
	 * Objects
	 */
	private ListBuilder listBuilder;
	
	public DL4JLayers(ListBuilder listBuilder) {
		this.listBuilder = listBuilder;
	}
	
	/*
	 * Add a dense layer
	 */
	public void addDenseLayer(int inputs, int outputs, Activation activation) {
		listBuilder.layer(new DenseLayer.Builder()
				.nIn(inputs)
				.nOut(outputs)
				.activation(activation)
				.build());
	}
	
	/*
	 * Add a output layer
	 */
	public void addOutputLayer(int inputs, int outputs, Activation activation, LossFunction lossFunction) {
		listBuilder.layer(new OutputLayer.Builder(lossFunction)
				.nIn(inputs)
				.nOut(outputs)
				.activation(activation)
				.build());
	}
}

```

#### Version Information

* Deeplearning4j version =  1.0.0-beta4
* Platform information (OS, etc) = Lubuntu 19.04
* CUDA version, if used = Not used
* NVIDIA driver version, if in use = No Nvidia here

#### Additional Information

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1787)
	at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls/javafx.scene.control.MenuItem.fire(MenuItem.java:465)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1380)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1333)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1782)
	... 43 more
Caused by: java.lang.ExceptionInInitializerError
	at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:701)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:268)
	at se.danielmartensson.deeplearning.DL4JModel.buildModel(DL4JModel.java:26)
	at se.danielmartensson.deeplearning.DL4J.initialModel(DL4J.java:60)
	at se.danielmartensson.controller.Front.New_Model(Front.java:92)
	... 54 more
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5768)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:202)
	... 59 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:213)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5765)
	... 60 more
```

Here is the pom.xml file

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>se.danielmartensson</groupId>
	<artifactId>JNonlinearControl</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>11.0.2</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-fxml</artifactId>
			<version>11.0.2</version>
		</dependency>
		<dependency>
			<groupId>org.datavec</groupId>
			<artifactId>datavec-api</artifactId>
			<version>1.0.0-beta4</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native</artifactId>
			<version>1.0.0-beta4</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>1.0.0-beta4</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-api</artifactId>
			<version>1.0.0-beta4</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-platform</artifactId>
			<version>1.0.0-beta4</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-api</artifactId>
			<version>1.0.0-beta4</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<release>11</release>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.openjfx</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>0.0.3</version>
				<configuration>
					<mainClass>se.danielmartensson.JNonlinearControl.Main</mainClass>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					<archive>
					  <manifest>
						<mainClass>se.danielmartensson.JNonlinearControl.Main</mainClass>
					  </manifest>
					</archive>
				</configuration><!--$NO-MVN-MAN-VER$-->
			</plugin>
		</plugins>
	</build>
</project>
```

#### Contributing

My project is here:
https://github.com/DanielMartensson/JNonlinearControl

Just run 
`mvn clean compile javafx:run`

Then `File -> New model` and then you just write something and press "save".

don't forget to install openjfx too.

`sudo apt-get install openjfx`
If you have deb-based Linux systems.

**Comment by RobAltena** [comment] 2019-08-03 01:59
While you have this error:

    org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an 
    nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html

There is no amount of JavaFX that can save you. 

You should only need one dependency to get the cpu Nd4j backend. 

     <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-native</artifactId>
        <version>${nd4j.version}</version>
    </dependency>

So lets take out all the others. 

I have just made sure my own little [hello world](https://github.com/RobAltena/HelloNd4J) runs with Ubuntu () and openjdk 11. But please try that yourself too.

**Comment by saudet** [comment] 2019-08-03 03:43
How is this not a duplicate of #8027?

**Comment by DanielMartensson** [comment] 2019-08-03 11:39
@saudet 
Not that solution for that was javafx-plugin-maven 0.0.3.  :)

**Comment by saudet** [comment] 2019-08-03 12:02
It's still most likely another issue with that plugin: Just try not to use it at all.

**Comment by DanielMartensson** [comment] 2019-08-03 12:07
> It's still most likely another issue with that plugin: Just try not to use it at all.

I have the conversation log here:
https://stackoverflow.com/questions/57085661/why-cant-i-compile-maven-with-openjfx-and-deeplearning4j

**Comment by DanielMartensson** [comment] 2019-08-03 14:23
SOrry

> While you have this error:
> 
> ```
> org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an 
> nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
> ```
> 
> There is no amount of JavaFX that can save you.
> 
> You should only need one dependency to get the cpu Nd4j backend.
> 
> ```
>  <dependency>
>     <groupId>org.nd4j</groupId>
>     <artifactId>nd4j-native</artifactId>
>     <version>${nd4j.version}</version>
> </dependency>
> ```
> 
> So lets take out all the others.
> 
> I have just made sure my own little [hello world](https://github.com/RobAltena/HelloNd4J) runs with Ubuntu () and openjdk 11. But please try that yourself too.

Sorry. I still got an error.

```
	/*
	 * Build model
	 */
	public void buildModel() {
		multiLayerConfiguration = listBuilder.build(); // <---- Here
		multiLayerNetwork = new MultiLayerNetwork(multiLayerConfiguration);
	}
```

```
Caused by: java.lang.ExceptionInInitializerError
	at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:701)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:268)
	at se.danielmartensson.deeplearning.DL4JModel.buildModel(DL4JModel.java:28)
	at se.danielmartensson.deeplearning.DL4J.initialModel(DL4J.java:60)
	at se.danielmartensson.controller.Front.New_Model(Front.java:93)
	... 54 more
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5768)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:202)
	... 59 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:213)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5765)
	... 60 more
```

**Comment by DanielMartensson** [comment] 2019-08-04 11:17
@saudet 

I need to use it, else it won't work for me.

**Closed** 2021-04-15 06:23 UTC
