### ISSUE TITLE
ND4J: isEmpty returns false when getting an Empty array

### ISSUE THREAD

**Issue by sercharpak** [eclipse/deeplearning4j#7930] opened 2019-06-21 09:29 UTC
#### Issue Description
Basically, I obtain an empty array when performing a **where** operation on a mask Boolean INDArray filled with false entries. I then collect the values using Scala's **collect** and obtain an empty Scala Array (it is therefore empty) and create an INDArray with it (also empty). 
* When asking the the **where** result if its empty, the current response is **false** when it should be **true**.
* When creating the final INDArray the **isEmpty** also returns **false**. Also its shape info is:
``` Rank: 1, DataType: DOUBLE, Offset: 0, Order: c, Shape: [0],  Stride: [1] ``` when Shape [0] was not implemented in the moment.

#### Reproduction
At first I have the array:
```
values: org.nd4j.linalg.api.ndarray.INDArray = [    0.1184,    0.8456,    0.9868,   -0.5301,    0.8014]
```
Then I threshold it with the value ```-20``` so I get:
```
scala>     val mask= values.lt(threshold )
mask: org.nd4j.linalg.api.ndarray.INDArray = [     false,     false,     false,     false,     false]
``` 
The first emtpy array I seem to get is when I apply the ```where```:
```
scala> val only_indices_mask_where_result = Nd4j.where(mask, null, null)
only_indices_mask_where_result: Array[org.nd4j.linalg.api.ndarray.INDArray] = Array([])
```
Then:
```
scala> val only_indices_mask = only_indices_mask_where_result(dim)
only_indices_mask: org.nd4j.linalg.api.ndarray.INDArray = []
```
Then, as an empty scala Array:
```
scala> val masked_values = only_indices_mask.toIntVector collect values.toDoubleVector
masked_values: Array[Double] = Array()
```
Who then becomes an empty INDArray:
```
scala> val masked_values_ndarray = Nd4j.create(masked_values)
masked_values_ndarray: org.nd4j.linalg.api.ndarray.INDArray = []
```
The ```isEmpty``` method returns false from the **where** result:
```
scala> only_indices_mask_where_result.isEmpty
res5: Boolean = false
```
But when asking for its shape I get an error :
```
scala> only_indices_mask_where_result.shapeInfoToString
<console>:44: error: value shapeInfoToString is not a member of Array[org.nd4j.linalg.api.ndarray.INDArray]
       only_indices_mask_where_result.shapeInfoToString
```
The final array also is detectes as **not empty**:
```
scala> masked_values_ndarray.isEmpty
res10: Boolean = false
scala> masked_values_ndarray.shapeInfoToString
res9: String = Rank: 1, DataType: DOUBLE, Offset: 0, Order: c, Shape: [0],  Stride: [1]
```

#### Version Information

* Deeplearning4j version: 1.0.0-beta4
* Linux

Obtained through an **uber jar** on Spark. The **pom** used is in this [gist](https://gist.github.com/sercharpak/d5a4408e1c9b50cb80f0c813f866c712)

**Comment by rnett** [comment] 2019-06-28 20:04
`Nd4j.where` doesn't return a NDArray, it returns an array of NDArrays.

So your `only_indices_mask_where_result` is a `Array[INDArray]`, with a single element (and thus isn't empty).  That element is an empty NDArray.

I can't reproduce your 2nd issue using
```kotlin
val d = Nd4j.create(doubleArrayOf())
println(d.shapeInfoToString())
println(d.isEmpty)
```
Which prints
```
Rank: 1, DataType: DOUBLE, Offset: 0, Order: c, Shape: [0],  Stride: [0]
true
```

Can you try it with a created empty double array instead of `masked_values` and see if you get the same result?

**Comment by AlexDBlack** [comment] 2019-06-29 01:51
"Zeros in shapes" wasn't supported as of beta4, so originally that was a bug. Now it is supported.
It should be working now, but I wanted an issue to ensure that it's working.
Once we've got a unit test to check this (and assuming it now all works) we can close this.

**Comment by raver119** [comment] 2019-07-05 12:11
```
@Test
    public void testEmptyWhere() {
        val mask = Nd4j.createFromArray(false,     false,     false,     false,     false);
        val result = Nd4j.where(mask, null, null);

        assertTrue(result[0].isEmpty());
        assertNotNull(result[0].shapeInfoDataBuffer().asLong());
    }
```

As far as i see not reproducible in current master. Shape function also works as expected.

**Closed by raver119** 2019-07-05 12:11 UTC
Labels: Bug, LIBND4J
