### ISSUE TITLE
Arbitrer-ui using logback 

### ISSUE THREAD

**Issue by talmal** [eclipse/deeplearning4j#8069] opened 2019-08-02 09:53 UTC
Hello,
i am trying to run the arbiter-ui, while using log4j implementation of slf4j, 
and i find that play.api.Logger.shutdown() is using logback, which stops me from using my choice of logger.

i am running the example code in /dl4j-examples/src/main/java/org/deeplearning4j/examples/arbiter/BasicHyperparameterOptimizationExample.java
with my logger of choice set.

i see it has already been discussed in other parts of the code 
https://github.com/eclipse/deeplearning4j/issues/6551
https://github.com/eclipse/deeplearning4j/issues/560
and yet i am unclear of what i should do to overcome this hard coded problem.

after excluding logback-classic from arbiter-ui_2.11, i am left with the ui server throwing an exception of java.lang.NoClassDefFoundError: ch/qos/logback/classic/LoggerContext
and the java process fails to exit/finish its run.

- after looking at other solutions to the problem i now catch the exception and present it as a log entry, but that does not help with the server hanging forever and the process not exiting the run.

#### Version Information
<dl4j.version>1.0.0-beta4</dl4j.version>
<slf4j.version>2.0.0-alpha0</slf4j.version>
<log4j-core.version>2.12.0</log4j-core.version>

* Deeplearning4j version 1.0.0-beta4
* Platform information (OS, etc) win7

#### Additional Information

Where applicable, please also provide:

    Exception in thread "main" java.lang.NoClassDefFoundError: 
    ch/qos/logback/classic/LoggerContext
    	at play.api.Logger$.shutdown(Logger.scala:303)
	at play.core.server.Server$class.stop(Server.scala:69)
	at play.core.server.NettyServer.stop(NettyServer.scala:175)
	at play.server.Server.stop(Server.java:28)
	at org.deeplearning4j.ui.play.PlayUIServer.stop(PlayUIServer.java:422)
	at app.DigitImageRecognizer.optimizeNetwork(DigitImageRecognizer.java:184)
	at app.DigitImageRecognizer.main(DigitImageRecognizer.java:88)
    Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.LoggerContext
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

#### Contributing
i am willing to help, but could use some guidance to what to do.

Thank you for a great framework,
Tal

**Comment by AlexDBlack** [comment] 2019-08-02 10:10
Related: https://github.com/eclipse/deeplearning4j/issues/3808

This isn't an arbiter restriction, this is a Play framework restriction.
Only option for us here is to upgrade the Play framework version (and just doing it in Maven isn't enough, IIRC there are API changes also). That's not a trivial task, but probably one that we should do anyway for other reasons (Play 2.4 is getting old... the only reason we're sticking with it is the Scala 2.10 support - see the aforementioned issue).

**Comment by talmal** [comment] 2019-08-02 13:30
i see, 

well right now i am calling System.exit() to end the program, do you think that extending the Play Server and overriding the logging part is a good idea ?

and about the bigger picture, is there a work plan on what needs to be done to upgrade the play/java9/java10, if you make a detailed plan it will be easy to make the change as a community effort.

**Comment by AlexDBlack** [comment] 2019-08-17 05:01
Closing this as a duplicate of this issue: https://github.com/eclipse/deeplearning4j/issues/3808

A fix for this issue (via Play framework version upgrade that allows configuring logging) will be merged soon: https://github.com/eclipse/deeplearning4j/pull/8098

**Closed by AlexDBlack** 2019-08-17 05:01 UTC
