### ISSUE TITLE
Nd4j initialization error on linux-ppc64le : library not found

### ISSUE THREAD

**Issue by montardon** [eclipse/deeplearning4j#8041] opened 2019-07-24 12:51 UTC
#### Issue Description
I created an uber jar with -Djavacpp.platform=linux-ppc64le

I run a demo on a Power PC. 

Errors appear when initializing Nd4j.

What is the compiler version used for generating libraries (found in distributed jars) ?

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 1.0.0-beta4
* Platform information (OS, etc) Power PC
* CUDA version, if used 10.1
* NVIDIA driver version, if in use I do not know but I guess > 410.

#### Additional Information

https://gist.github.com/montardon/82e9a51db6cbd73825b41b8955d976df

Found in libjnind4jcuda.so (using strings)
GCC_3.0
CXXABI_1.3.8
GLIBCXX_3.4.19
GLIBCXX_3.4.21
CXXABI_1.3
GLIBCXX_3.4
GLIBCXX_3.4.20
GLIBC_2.17

#### Contributing

I can help.

**Comment by saudet** [comment] 2019-07-24 23:22
Which version of Ubuntu? If you're trying to run this on Trusty 14.04, that's no longer supported by anyone as it has reached EOL in April.

**Comment by montardon** [comment] 2019-07-25 12:02
I am not using Ubuntu but a RedHat.

**Comment by saudet** [comment] 2019-07-25 12:16
Ah, I see. Indeed, we're considering switching ours builds to RHEL/CentOS, see issue #6805. One problem we would have though is to figure out how to cross compile with RHEL/CentOS, since a lot of the binaries are actually built on Travis CI at the moment: https://travis-ci.org/bytedeco/javacpp-presets Ubuntu is pretty good for that, while RHEL/CentOS isn't, but if you do figure out something, please let me know. Anyway, let's continue the discussion on the duplicate thread.

**Comment by saudet** [comment] 2019-07-25 12:17
Duplicate of #6805

**Closed by saudet** 2019-07-25 12:17 UTC
Labels: C++, DevOps, Duplicate, ND4J
