### ISSUE TITLE
Empty summary with Keras model import

### ISSUE THREAD

**Issue by fbaranski** [eclipse/deeplearning4j#7799] opened 2019-05-28 14:56 UTC
#### Issue Description

I am trying to import and run a Keras model (in Scala). After import, the model summary seems empty.
`val model = KerasModelImport.importKerasModelAndWeights( "./full_model.h5")
model.summary()`

I get 
`============================================================================================================================================================================================================================================================================================================================================================================
VertexName (VertexType)                 nIn,nOut   TotalParams   ParamsShape            Vertex Inputs
=============================================================================================================================================================================================================================================================================================...`

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 1.0.0-beta4
* Scala version : 2.12.8
* platform information (OS, etc) : MacOS Mojave

**Comment by fbaranski** [comment] 2019-05-29 07:22
Here the diagram of the ComputationGraph
![model](https://user-images.githubusercontent.com/19794759/58537402-1d4afb00-81f3-11e9-9a9a-964cc34faa9f.png)
There are several EmbeddingLayers, to manage categorial variables, the last one to manage numerical variables.

**Comment by maxpumperla** [comment] 2019-05-29 10:08
@fbaranski thanks for reporting. can you please attach your model? Otherwise I can't reproduce anything.

also, appart from not having the correct summary, do you experience other problems? e.g. can you make predictions with the model?

**Comment by fbaranski** [comment] 2019-05-29 15:34
Please find the model (h5 format).
[full_model.zip](https://github.com/deeplearning4j/deeplearning4j/files/3233219/full_model.zip)
No, I can't, because I do not know how to put inputs.
For instance I get the following error.
`val output: Array[INDArray]=model.output(false, inputs, null)
java.lang.IllegalStateException: Invalid input: EmbeddingSequenceLayer expects either rank 2 input of shape [minibatch,seqLength] or rank 3 input of shape [minibatch,1,seqLength]. Got rank 1 input of shape [1]
 at org.deeplearning4j.nn.layers.feedforward.embedding.EmbeddingSequenceLayer.preOutput(EmbeddingSequenceLayer.java:110)
 at org.deeplearning4j.nn.layers.feedforward.embedding.EmbeddingSequenceLayer.activate(EmbeddingSequenceLayer.java:168)
 at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:111)
 at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2355)
 at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1737)
 at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1693)
 at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1679)
 ... 36 elided`

**Comment by AlexDBlack** [comment] 2019-05-30 01:12
@fbaranski 
> EmbeddingSequenceLayer expects either rank 2 input of shape [minibatch,seqLength] or rank 3 input of shape [minibatch,1,seqLength]. Got rank 1 input of shape [1]

the error itself tells you what the layer expects.
Basically, the input should be a `[minibatch,seqLength]` shape array with values equal to the integer indices of the tokens. So input[x,y] is the yth token index for the xth minibatch. Note it's zero indexed.

**Comment by fbaranski** [comment] 2019-06-03 08:51
Thanks @AlexDBlack .
Could you give an example in Scala for the input?

**Comment by fbaranski** [comment] 2019-06-12 17:41
Hi @AlexDBlack . Could you help by giving me an example on how to do prediction with this model?
Thanks in advance

**Comment by agibsonccc** [comment] 2021-02-01 01:25
Closing, not relevant anymore.

**Closed by agibsonccc** 2021-02-01 01:25 UTC
Labels: DL4J Keras
