### ISSUE TITLE
Keras MobileNet import is not functioning

### ISSUE THREAD

**Issue by TobiasGoerke** [eclipse/deeplearning4j#6171] opened 2018-08-15 20:58 UTC
As already pictured in [this issue](https://github.com/deeplearning4j/deeplearning4j/issues/6161), I am having some trouble getting to run the MobileNet model using Keras' model import.

While I can import and run any other Keras model without any problems, it does not work for the MobileNet model provided in dl4j-test-resources as it throws a `DL4JInvalidInputException`. 
Thus, I suspect the problem to lie within the model.

I have created a Maven example you may pull here: [https://github.com/TobiasGoerke/MobileNetKerasImportTest](https://github.com/TobiasGoerke/MobileNetKerasImportTest)

Thanks!

**Comment by maxpumperla** [comment] 2018-08-15 21:20
great. I'll pick it up tomorrow. thanks

**Comment by TobiasGoerke** [comment] 2018-08-16 07:42
Alright, thanks a lot for your support

**Comment by maxpumperla** [comment] 2018-08-21 10:52
@TobiasGoerke thanks again, fixed now

**Comment by maxpumperla** [comment] 2018-08-21 14:31
@TobiasGoerke sorry, I have completely misunderstood you. "ReLU" is indeed not a standard Keras layer type. You either have explicit activations within the layer or an "Activation" layer. I'll look more into this at a later point....

**Comment by TobiasGoerke** [comment] 2018-08-21 14:44
As the original paper specifies ReLU as a component does that mean pre-trained models cannot be imported?
Anyways, I am looking forward to your findings :+1:

**Comment by berkgulay** [comment] 2018-12-28 21:20
Same issue on my side as well. I am facing with either "Unsupported keras layer type Model" error or "Unsupported keras layer type ReLU" error while trying to import pretrained MobileNetV2 model. I think the reason of that is Keras' encoding type of pre-trained(application) models in config json. Keras directly adds a layer as "Model" to cover all mobilenet architecture like a container. But at the same time when we try to flatten this pre-trained model, DL4J throws "Unsupported keras layer type ReLU" exception this time. Thus we cant go further either ways. I guess this structure should be supported by DL4J in some way. Otherwise, we cant import really meaningful Keras models. Thanks...

**Comment by mmgweiyang** [comment] 2019-10-21 08:00
I am encountering the same issue when importing a pre-trained Keras mobile net.
Want to know when this issue can be fixed?

**Comment by Hyberlion** [comment] 2019-11-12 08:01
> I am encountering the same issue when importing a pre-trained Keras mobile net.
> Want to know when this issue can be fixed?

This problem is caused by keras updating (I guess). You can change the class name of "ReLU" into "Activation", which dl4j has supported. Here is the example code you can reference:
https://github.com/alessandrocapotondi/mobilenet_v1_stmcube_ai/blob/master/keras_model/keras_mobilenet_stm_cubemx_ai.ipynb

**Comment by jelmerk** [comment] 2019-12-15 13:54
This is still an issue with dl4j 1.0.0-beta6  ... any chance this will be addressed ?

**Comment by AlexDBlack** [comment] 2019-12-16 11:16
This one got missed/forgotten sorry, it shouldn't be too hard to add.

**Closed** 2020-01-04 02:45 UTC
Labels: Bug, DL4J Keras

**Comment by AlexDBlack** [comment] 2020-01-04 02:46
Thanks for reporting this.
It has been fixed here, and will be merged back to eclipse/deeplearning4j shortly. The fix will be available on snapshots within a few days.
https://github.com/KonduitAI/deeplearning4j/pull/143/
https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots
