### ISSUE TITLE
windows CUDA org.bytedeco.javacpp.Loader.loadLibrary Error

### ISSUE THREAD

**Issue by jossbetel** [eclipse/deeplearning4j#7909] opened 2019-06-17 23:03 UTC
#### Issue Description
every time I try to use CUDA 10.1 with G1080 then
java.lang.UnsatisfiedLinkError  repeated  when I try to run.
if i change the config "<nd4j.backend>nd4j-cuda-10.1-platform</nd4j.backend>" to 
"<nd4j.backend>nd4j-native-platform</nd4j.backend>" then every thing goes well....
...................
i swift my opt system to ubuntu 19.04 then everything is A ok.....
...................
why i can't used GPU model in windows.
get me a help....3Q

Please describe our issue, along with:
- expected behavior
the expected show that the thing"jnicusparse.dll" is UnsatisfiedLinkError
I use my explore to check out what is going on.
then I find the jnicusparse.dll is right that in the possition.

- encountered behavior
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Administrator\.javacpp\cache\cuda-10.1-7.5-1.5-windows-x86_64.jar\org\bytedeco\cuda\windows-x86_64\jnicusparse.dll: 找不到指定的程序。
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1316)
	... 28 more
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 1.0.0-beta4
* platform information (OS, etc) windows 10 x64 
* CUDA version, if used 10.1
* NVIDIA driver version, if in use 425.25

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment] 2019-06-18 00:59
Can you do 3 things:
1. Post your full pom.xml
2. Describe how you are running your program - though IDE (eclipse, intellij, netbeans etc) or through maven?
3. Post the output of `nvcc --version`

**Comment by saudet** [comment] 2019-06-18 01:20
Duplicate of #7781

Add the following dependencies to your pom.xml file:
https://github.com/bytedeco/javacpp-presets/tree/1.5/cuda#the-pomxml-build-file

**Closed by saudet** 2019-06-18 01:20 UTC
Labels: Duplicate, ND4J, Question

**Comment by jossbetel** [comment] 2019-06-18 05:08
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.betel</groupId>
    <artifactId>jossdeep</artifactId>
    <version>0.0.1a</version>
    <properties>
        
        <nd4j.backend>nd4j-cuda-10.1-platform</nd4j.backend>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
        <nd4j.version>1.0.0-beta4</nd4j.version>
        <dl4j.version>1.0.0-beta4</dl4j.version>
        <datavec.version>1.0.0-beta4</datavec.version>
        <arbiter.version>1.0.0-beta4</arbiter.version>
        <rl4j.version>1.0.0-beta4</rl4j.version>
        
        <scala.binary.version>2.11</scala.binary.version>
    </properties>
    <dependencies>
        
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>${nd4j.backend}</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-api</artifactId>
            <version>${datavec.version}</version>
        </dependency>
        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-local</artifactId>
            <version>${datavec.version}</version>
        </dependency>
        
        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.18</version>
        </dependency>
        
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui_${scala.binary.version}</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
    </dependencies>
</project>

**Comment by jossbetel** [comment] 2019-06-18 05:10
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.betel</groupId>
    <artifactId>jossdeep</artifactId>
    <version>0.0.1a</version>
    <properties>
        
        <nd4j.backend>nd4j-cuda-10.1-platform</nd4j.backend>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
        <nd4j.version>1.0.0-beta4</nd4j.version>
        <dl4j.version>1.0.0-beta4</dl4j.version>
        <datavec.version>1.0.0-beta4</datavec.version>
        <arbiter.version>1.0.0-beta4</arbiter.version>
        <rl4j.version>1.0.0-beta4</rl4j.version>
        
        <scala.binary.version>2.11</scala.binary.version>
    </properties>
    <dependencies>
        
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>${nd4j.backend}</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-api</artifactId>
            <version>${datavec.version}</version>
        </dependency>
        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-local</artifactId>
            <version>${datavec.version}</version>
        </dependency>
        
        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.18</version>
        </dependency>
        
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui_${scala.binary.version}</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
    </dependencies>
</project>

**Comment by jossbetel** [comment] 2019-06-18 05:14
2.Describe how you are running your program - though IDE (eclipse, intellij, netbeans etc) or through maven?
I running my program with intellij IDEA 2019.3 and My maven version is 3.6.1

3.Post the output of nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:11:20_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.168

**Comment by AlexDBlack** [comment] 2019-06-18 05:37
@jossbetel @saudet already mentioned what you should do to fix this:

> Duplicate of #7781
> Add the following dependencies to your pom.xml file:
https://github.com/bytedeco/javacpp-presets/tree/1.5/cuda#the-pomxml-build-file

**Comment by jossbetel** [comment] 2019-06-18 13:45
@AlexDBlack 3Q,very much. I work smoothly, then. Thank you for all that you have done.

**Comment by jossbetel** [comment] 2019-06-18 13:59
@saudet And,Thanks too. yeah,I take my hats off to you all.
