### ISSUE TITLE
Not able to Run nd4j in Jupyter with IJava kernel 

### ISSUE THREAD

**Issue by AkbarAlam** [eclipse/deeplearning4j#7937] opened 2019-06-22 08:07 UTC
#### Issue Description

I am trying to use Dl4j and Nd4j in Jupyter with [IJava](https://github.com/SpencerPark/IJava) kernel. I am always getting error. which is 

```
---------------------------------------------------------------------------
java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j
	at .(#19:1)
```

I have added the following as my dependencies

```
%%loadFromPOM
<dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-core</artifactId>
    <version>1.0.0-beta4</version>
</dependency>

<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-api</artifactId>
    <version>1.0.0-beta4</version>
</dependency>

<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native-platform</artifactId>
    <version>1.0.0-beta4</version>
</dependency>

<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.7.5</version>
</dependency>
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.6.4</version>
</dependency>
 
```

and then 

```
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

INDArray inputX = Nd4j.rand(5,3);
```

Am I doing something wrong or this is a real issue? Researchers like me love to use Jupyter and we want to use Dl4J

**Comment by saudet** [comment] 2019-06-23 00:19
The cause of the error should show up in the stack trace. Could you post the whole stack trace?

**Comment by AkbarAlam** [comment] 2019-06-23 08:35
in Jupyter I am getting only that output. there is nothing on the console

**Comment by saudet** [comment] 2019-06-23 08:49
Ok, could you set the `org.bytedeco.javacpp.logger.debug` property to `true` and let me know what that outputs to the console?

**Comment by AkbarAlam** [comment] 2019-06-24 21:25
i am not able to set that in jupyter

**Comment by AkbarAlam** [comment] 2019-06-24 21:31
this is really frustrating. we want to use java nd4j and dl4j but not really able to use it in a notebook.

**Comment by ShamsUlAzeem** [comment] 2019-06-25 02:54
@AkbarAlam how did you load the dependencies into the paragraphs?

**Comment by wmeddie** [comment] 2019-06-25 02:55
@AkbarAlam We have been using DL4J in Jupyter, BeakerX, and Zeppelin.  It should just work if you add the dependencies.  Can you post the notebook or configuration to this issue?

**Comment by ShamsUlAzeem** [comment] 2019-06-25 02:58
Also, can you use %maven magic and try again in place of %%loadFromPOM?

**Comment by AkbarAlam** [comment] 2019-06-25 18:12
@wmeddie I am using Java 12. do you think that could be reason ?
@ShamsUlAzeem Have you tried that ?I did same result

**Comment by agibsonccc** [comment] 2019-06-26 02:51
@AkbarAlam Could you post more of your error? To get beaker working, there's some special threading mechanisms we had to do. I'm guessing this would work:
Thread.currentThread().setContextClassLoader(Nd4j.class.getClassLoader());

**Comment by ShamsUlAzeem** [comment] 2019-06-27 08:14
@AkbarAlam Hmm... can you also try putting them under the <dependencies> tag?

**Comment by AkbarAlam** [comment] 2019-06-28 12:16
@ShamsUlAzeem that did not work. i have tried it

**Comment by agibsonccc** [comment] 2020-08-18 23:50
Closing this. I technically got this working. We have a relevant PR that also allows you to specify a specialized classloader as well: https://github.com/eclipse/deeplearning4j/pull/8972

**Closed by agibsonccc** 2020-08-18 23:50 UTC
