### ISSUE TITLE
ND4J: INDArray.match(INDArray, Condition) issue

### ISSUE THREAD

**Issue by RobAltena** [eclipse/deeplearning4j#8166] opened 2019-08-29 01:30 UTC
#### Issue Description
Having some trouble getting [INDArray match(INDArray, Condition)](https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/INDArray.java#L654) to run. No usage found, no tests found.

This test:
    
    @Test
    void testMatch1() {

        INDArray x = Nd4j.ones(DataType.FLOAT, 3,3);
        INDArray y = Nd4j.ones(DataType.FLOAT, 3,3);
        Condition c =  Conditions.lessThan(0.0f);

        INDArray z = x.match(x, c);
    }

throws: java.lang.IllegalArgumentException: Op.Z type must be bool: z.datatype=FLOAT for op class org.nd4j.linalg.api.ops.impl.transforms.bool.MatchConditionTransform

How should the method be used? (Maybe these methods should be removed or deprecated?)

**Comment by AlexDBlack** [comment] 2019-08-29 03:08
As noted in slack, this looks like a bug to me
https://github.com/eclipse/deeplearning4j/blob/f03b0ee78f220c7cd1b0b9f80dceaf04b3d16308/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L2022

That's `MatchConditionTransform(x,z,condition)`, instead of (x,y,condition).
i.e., the comparison array is passed as the result array.

**Comment by AlexDBlack** [comment] 2019-10-24 05:47
So, there's more to the problem here than just the constructor, and the fact that we need no-arg conditions like `Conditions.lessThan()` for the pairwise case...
After adding an (x,y,z) constructor and using that in BaseNDArray, I'm getting incorrect values for the pairwise x = y case:
```
    @Test
    public void testMatch1() {

        INDArray x = Nd4j.ones(DataType.FLOAT, 3,3);
        INDArray y = Nd4j.linspace(DataType.FLOAT, -5, 9, 1).reshape(3, 3);
        Condition c =  Conditions.equals(0.0);

        System.out.println("Y:\n" + y);

        INDArray z = x.match(y, c);
        INDArray exp = Nd4j.createFromArray(new boolean[][]{
                {false, false, false},
                {false, false, false},
                {true,  false, false}
        });

        assertEquals(exp, z);
    }
```
```
Y:
[[   -5.0000,   -4.0000,   -3.0000], 
 [   -2.0000,   -1.0000,         0], 
 [    1.0000,    2.0000,    3.0000]]
```

![image](https://user-images.githubusercontent.com/2360237/67456824-aae52680-f67d-11e9-9660-c96ce5e0ffc3.png)

**Comment by raver119** [comment] 2019-11-20 14:22
Technically this is not a bug.

Originally MatchCondition operation works in Scalar-only mode, so comparable is always an argument, and it belongs to two op groups: TransformBool and ReduceLong. Returning either mask or number of elements that match condition.

**Comment by raver119** [comment] 2019-11-20 17:44
Implemented in my branch, will be merged later.

**Closed by raver119** 2019-11-20 17:44 UTC
Labels: Bug, ND4J
